[workspace]
members = ["crates/*", "integration_tests"]

[workspace.dependencies]
common = { path = "./crates/common" }
interface = { path = "./crates/interface" }
adapter = { path = "./crates/adapter" }
