[workspace]
members = ["crates/*", "integration_tests", "xtask"]
resolver = "2"
[workspace.dependencies]
common = { path = "./crates/common" }
dap = { path = "./crates/dap" }
interface = { path = "./crates/interface" }
adapter = { path = "./crates/adapter" }

