[package]
name = "tests"
version = "0.0.0"
edition = "2021"

[dependencies]
common.workspace = true
adapter.workspace = true
interface.workspace = true
dap.workspace = true

[[test]]
name="breakpoints"
path="breakpoints.rs"
